services:
    php:
        build: # Info to build the Docker image
            context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
            dockerfile: PHP83-Dockerfile # Specify the name of the Dockerfile
        ports:
            - 8111:80
        depends_on:
            - redmine-dev
        volumes:
            - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*

    redmine-dev:
        image: redmine:5.1.4
        user: "1000:1000"
        ports:
            - "3000:3000"
        environment:
            REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-dev_data/files:/usr/src/redmine/files
            - ./.docker/redmine-dev_data/sqlite:/usr/src/redmine/sqlite

    # Make sure the following services are configured in:
    # - /tests/Behat/behat.yml

    redmine-50104:
        image: redmine:5.1.4
        user: "1000:1000"
        ports:
            - "5103:3000"
        environment:
            REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-50104_data/files:/usr/src/redmine/files
            - ./.docker/redmine-50104_data/sqlite:/usr/src/redmine/sqlite

    redmine-50010:
        image: redmine:5.0.10
        user: "1000:1000"
        ports:
            - "5009:3000"
        environment:
            REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-50010_data/files:/usr/src/redmine/files
            - ./.docker/redmine-50010_data/sqlite:/usr/src/redmine/sqlite
